# Generated by Django 4.2.7 on 2023-11-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_name_alter_user_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(max_length=100, verbose_name='Second name'),
        ),
    ]
